dynaconf_merge = true

# DO NOT CHANGE THIS FILE to alter the configuration.
# instead, create a config.user.toml file in your
# project folder and override the values you need.

[tls]
# The paths to TLS cert and key the whole application should use for things.
# if these aren't set right, TLS won't engage.
certificate = "localhost.pem"
key = "localhost-key.pem"

[postgresql]
# The information that'll be fed straight into
# asyncpg's connection function via **kwargs.
dsn = "postgres://muforge:muforge@localhost:5432/muforge"

[jwt]
# These are the defaults for the JWT tokens.
# They can be overridden by the user.
# PLEASE CHANGE THE SECRET IN YOUR config.user.toml file!
algorithm = "HS256"
secret = "CHANGE_ME_DAMMIT"
token_expire_minutes = 30
# 7 days in minutes.
refresh_expire_minutes = 10080

[shared]
# The external IP address to bind to.
# This will be used for binding all of the portal's listening
# ports, and also the game's webserver.
external = "0.0.0.0"
# the class that'll be used to handle the launcher.
launcher = "muforge.utils.Launcher"
# The name of the project.

[mssp]
# the following values will fill the MSSP (MUD Server Status Protocol)
# dictionary that's sent to clients that request it.
# Put all static information here. dynamic information like PLAYERS
# will be filled in by the server.
NAME = "muforge"
CHARSET = "UTF-8"
CODEBASE = "muforge"
FAMILY = "Custom"
"CRAWL DELAY" = -1
PORT = 7000
SSL = 7001

ANSI = 1
UTF-8 = 1
"XTERM 256 COLORS" = 1
"XTERM TRUE COLORS" = 1

[portal.networking]
# The port that normal telnet will listen on. Set to 0 to disable.
telnet = 7000
# The port that secure telnet (TLS) will listen on. Set to 0 to disable.
telnets = 7001
# The port that SSH will listen on. Set to 0 to disable.
ssh = 7002
# The Link will attempt to connect to this address after negotiations to connect to the game
# via SocketIO. It will also be provided to all webclients. So, it should be your external domain
# name/url or IP address.
game_url = "https://127.0.0.1:8000"

[portal.classes]
# The key-values here are used to fill the muforge.CLASSES dictionary
# on boot. It's done for caching purposes.
# This makes the project very moddable as you can specify whichever
# classes you want to be used for X purposes.

# The class that'll be used to handle the portal.
application = "muforge.portal.application.Application"
# The class that'll be used to handle the portal's telnet/ssh connections.
# it inherits from muforge.portal.base_connection.BaseConnection
# so anything that wants to change the behavior of the connection
# should inherit from telnet.
telnet_connection = "muforge.portal.telnet.TelnetConnection"
ssh_connection = "muforge.portal.ssh.SSHConnection"
# The parsers that interpret user commands at different states.
login_parser = "muforge.portal.parsers.login.LoginParser"
user_parser = "muforge.portal.parsers.user.UserParser"
character_parser = "muforge.portal.parsers.character.CharacterParser"

[portal.services]
# Classes that'll be launched by the portal when it boots.
telnet = "muforge.portal.telnet.TelnetService"
telnets = "muforge.portal.telnet.TLSTelnetService"

[portal.commands]
# These commands are imported by the character_parser.
# The key only matters for overrides or disables. All callables
# from the module are loaded.
system = "muforge.portal.commands.system"
help = "muforge.portal.commands.help"

[events]
system = "muforge.events.system"
characters = "muforge.events.characters"

[game.classes]
# The key-values here are used to fill the muforge.CLASSES dictionary
# on boot. It's done for caching purposes.
# This makes the project very moddable as you can specify whichever
# classes you want to be used for X purposes.

# The class that'll be used to handle the game.
application = "muforge.game.application.Application"

[game.lockfuncs]
# The key is only used for overrides or disables. It loads all functions defined
# in the module which do not begin with an underscore.
#base = "muforge.game.lockfuncs"

[game.networking]
# governs who is allowed to use X-Forwarded-For and have it respected.
# This should really only be your proxy servers or the host running
# the portal.
trusted_proxy_ips = ["127.0.0.1"]
port = 8000

[fastapi.routers]
# every module listed here must have a global named
# "router" to be imported.
# The key is the mount path. like /auth or /users
auth = "muforge.game.routers.auth"
users = "muforge.game.routers.users"
characters = "muforge.game.routers.characters"
system = "muforge.game.routers.system"
